import streamlit as st
from textwrap import dedent
from components.topbar import render_topbar


def render_overview():
    render_topbar()

    st.markdown(dedent("""
<div class="card">
    <div style="display:grid;grid-template-columns:2fr 1fr;align-items:center;">
        <div class="asset-title">Total Account Assets</div>
        <div>
            <div class="metric-label" style="text-align:right;">DAILY GAIN/LOSS</div>
            <div class="big-gain">--</div>
        </div>
    </div>
</div>

<div class="card">
    <div class="table-row">
        <div class="table-head">ASSET NAME / VALUE</div>
        <div class="table-head">DAILY RETURN</div>
        <div class="table-head">SECTOR PERFORMANCE</div>
        <div class="table-head">TOTAL HOLDINGS</div>
    </div>

    <div class="empty-table-row">
        Portfolio data placeholder · to be connected with backend API
    </div>

    <div class="cyan" style="margin-top:18px;">＋ ADD NEW HOLDING</div>
</div>

<div class="card">
    <div style="display:grid;grid-template-columns:2fr 1fr;align-items:center;">
        <div class="section-title">AI Portfolio Analysis</div>
        <div style="text-align:right;">
            <span class="select-pill">AI Assistant Selection ▾</span>
        </div>
    </div>
</div>

<div class="card">
    <div class="table-head">
        SIGNAL INDICATOR:
        <span class="dot red-dot"></span> Red
        <span class="dot green-dot"></span> Green
        <span class="dot yellow-dot"></span> Yellow
    </div>

    <div class="section-label">DETAILED ANALYSIS:</div>
    <div class="empty-analysis">
        AI portfolio analysis placeholder · generated by backend AI service
    </div>

    <div class="section-label">REBALANCING SUGGESTIONS:</div>
    <div class="suggestion">Backend AI will return rebalancing suggestions here.</div>
    <div class="suggestion" style="border-left-color:#374151;">Backend API placeholder for second suggestion.</div>
</div>

<div class="floating-btn">+</div>
"""), unsafe_allow_html=True)